Things
lpereira/lwan pull request #328
Opened 2022-01-21 09:27 UTC by pontscho

Hey,

I've made some small patches that makes my life easier, I thought I share with these with You. Maybe it can be useful for others too.

 * fixing build on macOS: I won't able to build on my notebook without these small changes.
 * enabling luajit 2.1: I've started to use openresty's fork about luajit, this version has a lot's of performance optims and they are maintaining it actively 
 * making brotli/zstd optional (enabled by default): zstd and brotli is installed on my notebook but doesn't really need these support for me, I've added two cmake options for it
 * allow remote address override by X-Real-IP: I've started to use nginx for TLS and HTTP2 termination, nginx supports more flexible routing and acl management supports than hitch but by default the remote address will be determined to a localhost. With adding X-Real-IP header possible to log out the real IP address.

Thanks,
pontscho

2022-01-22 00:46 UTC, lpereira commented
As far as the `X-Real-IP` header goes, it [seems like you can use the PROXY protocol on nginx for outgoing connections too](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/#proxy-protocol-for-a-tcp-connection-to-an-upstream); Lwan already supports that.  I would prefer Lwan to support only one scheme for this feature.

2022-01-22 00:48 UTC, lpereira commented
Thanks for the PR! I'll look at them more carefully whenever I have some time.

2022-01-24 08:30 UTC, pontscho commented
> As far as the `X-Real-IP` header goes, it [seems like you can use the PROXY protocol on nginx for outgoing connections too](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/#proxy-protocol-for-a-tcp-connection-to-an-upstream); Lwan already supports that. I would prefer Lwan to support only one scheme for this feature.

Yep, It's right, I've tried it, stream proxy is almost a good way but in that case I lost the HTTP2 termination and that is important for me.

2022-01-24 08:31 UTC, pontscho commented on src/lib/missing/sys/epoll.h
> +typedef enum { EPOLL_CTL_ADD, EPOLL_CTL_MOD, EPOLL_CTL_DEL } epoll_op;
Okay, I will check it.

2022-02-06 12:54 UTC, pontscho commented on src/lib/missing/sys/epoll.h
> +typedef enum { EPOLL_CTL_ADD, EPOLL_CTL_MOD, EPOLL_CTL_DEL } epoll_op;
Yep, it okay.

2022-02-06 16:40 UTC, lpereira commented
Thanks for confirming! Will cherry pick the others, then

On Sun, Feb 6, 2022, at 4:54 AM, pontscho wrote:
> 
> 
> ***@***.**** commented on this pull request.
> 
> 
> In src/lib/missing/sys/epoll.h <https://github.com/lpereira/lwan/pull/328#discussion_r800176052>:
> 
> > @@ -32,9 +32,9 @@ enum {
>      EPOLLHUP = EPOLLRDHUP
>  } epoll_event_flag;
>  
> -enum { EPOLL_CTL_ADD, EPOLL_CTL_MOD, EPOLL_CTL_DEL } epoll_op;
> +typedef enum { EPOLL_CTL_ADD, EPOLL_CTL_MOD, EPOLL_CTL_DEL } epoll_op;
> 
> Yep, it okay.
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/lpereira/lwan/pull/328#discussion_r800176052>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAADVGMNH7YU43YXNLH5IDLUZZVPVANCNFSM5MPAIDYQ>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you commented.Message ID: ***@***.***>
>

2022-02-07 19:20 UTC, pontscho commented
Hi,

I've added some other patches to my fork,

1. I increased the HTTP header buffer four times because 512 bytes wasn't enough in some cases in practice (for example I use a littlebit more complex cookie, content encoding and some other headers for debugging)
2. I've fixed epoll.h on macos
3. maybe this patch that you won't like :) I moved the read_cpu_topology() function to lwan.c and read this information from /sys before lwan call chroot(). With this change is possible to avoid needs for /sys in chrooted environment.

Thank you very much for other applying my patches. 
pontscho

2022-02-07 19:22 UTC, lpereira commented
I thank you for working on Lwan! I'll cherry pick these patches as soon as I have some free time

On Mon, Feb 7, 2022, at 11:20 AM, pontscho wrote:
> 
> 
> Hi,
> 
> I've added some other patches to my fork,
> 
>  1. I increased the HTTP header buffer four times because 512 bytes wasn't enough in some cases in practice (for example I use a littlebit more complex cookie, content encoding and some other headers for debugging)
>  2. I've fixed epoll.h on macos
>  3. maybe this patch that you won't like :) I moved the read_cpu_topology() function to lwan.c and read this information from /sys before lwan call chroot(). With this change is possible to avoid needs for /sys in chrooted environment.
> 
> Thank you very much for other applying my patches.
> pontscho
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/lpereira/lwan/pull/328#issuecomment-1031829153>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAADVGPZBSCAEF5EPKKXUPLU2ALQVANCNFSM5MPAIDYQ>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you commented.Message ID: ***@***.***>
>

2022-02-10 21:26 UTC, lpereira commented
I would prefer if you sent a new PR for each kind pack of related changes you're making. If you keep adding commits to this PR, it'll be a bit hard for me to review. (I don't have much time to work on Lwan anymore, unfortunately.)

2022-02-10 21:51 UTC, lpereira requested changes
Thanks for the PR! I appreciate you hacking on this, especially while trying to improve macOS support -- which I never use, so it's frequently broken, especially now that the macOS build bot is not active.

I do have some questions and comments, however:

2022-02-10 21:51 UTC, lpereira commented on src/lib/lwan.c
> +    int logical_cores = 1; sysctlbyname("hw.logicalcpu", &logical_cores, &length, NULL, 0);
There's no need to write code that is this terse; please spread this out and do error checking when calling `sysctlbyname()`.

2022-02-10 21:51 UTC, lpereira commented on src/lib/lwan.c
> +    }
This won't work in all cases -- it's not always that `cpu[i]` is a sibling of `cpu[i+1]`.  CPU topologies vary quite a bit; that's why it's that complex to do it on the Linux version of this code. (I also suspect that the Linux code is a bit wrong here; it doesn't seem to give the correct results on my laptop.  I don't have access to -- or care about -- NUMA machines and that may make things even more wrong.)

The topology is important in the scheduling code because of the way memory is allocated and the connection array is laid out; it's made like this to avoid [false sharing](https://en.wikipedia.org/wiki/False_sharing) when accessing that array. (There are other reasons, including the usage of `SO_INCOMING_CPU` or the CBPF code that hints the kernel to process the interrupts in the same CPU that will handle the connection in Lwan to avoid having to potentially migrate stuff between cores.)

2022-02-10 21:51 UTC, lpereira commented on src/lib/lwan-websocket.c
> +        *((uint16_t *)(frame + 2)) = htons((uint16_t)len);
This can be an issue on systems where unaligned access is either not possible, or there's a performance penalty for doing so. It's better to just use `memcpy()`; the compiler knows about it and can generate similar code if the length is known at compile time.

2022-02-10 21:51 UTC, lpereira commented on src/lib/lwan-thread.c
> +#if (defined(__x86_64__) && defined(__linux__)) || defined(__APPLE__)
This `#ifdef` thing is starting to look like a maze. Might be easier to move this to a file of its own where it's clearer what's happening.

2022-02-10 21:51 UTC, lpereira commented on src/lib/lwan-request.c
> +        strncpy(buffer, request->helper->xrealip.value, len), buffer[len] = 0;
Please write one statement per line. I missed the `buffer[len]` the first time I read this.

2022-02-10 21:51 UTC, lpereira commented on src/lib/lwan-request.c
> +            break;
This function is a really hot spot while parsing requests, and I'd like to really think about adding things here that most users won't need -- especially since Lwan also supports the PROXY protocol that covers this use case.

If this ends up being integrated, I'd rather see something like what we do for Cookies, where we look for the header if and only if a handler requests it, parse them, and sets a flag to avoid having to look for the header again. I'm not really convinced, however, that also supporting this header is necessary, either, given how prevalent PROXY protocol is.

2022-02-10 21:51 UTC, lpereira commented on src/lib/lwan.c
> +                    parse_bool(line->value, default_config.allow_remote_address_override);
Given we also support the PROXY protocol for the same thing, it might be a better idea to see a single configuration option for both features (e.g. `allow_spoofing_origin_ip = [x-real-ip] [PROXY]`).

2022-02-10 21:51 UTC, lpereira commented on src/lib/lwan-websocket.c
> +void lwan_response_websocket_write(struct lwan_request *request, bool is_text)
For legibility reasons, it might be better to have two new functions: `lwan_response_websocket_write_text()`and `lwan_response_websocket_write_binary()`, calling this function with either a `WS_OPCODE_TEXT` or `WS_OPCODE_BINARY` parameter. This avoids the branch and removes a boolean parameter to a function (which is sometimes tricky to reason about in the calling site).

2022-02-12 11:38 UTC, pontscho commented on src/lib/lwan-websocket.c
> +void lwan_response_websocket_write(struct lwan_request *request, bool is_text)
First time I created same API both for C and Lua API (ws_text(), ws_binary(), etc) but I wanted keep backward compatibility with current existing API live ws_write. I will change it back for my original thoughts.

2022-02-12 11:39 UTC, pontscho commented on src/lib/lwan.c
> +                    parse_bool(line->value, default_config.allow_remote_address_override);
Okay.

2022-02-12 11:39 UTC, pontscho commented on src/lib/lwan-request.c
> +        strncpy(buffer, request->helper->xrealip.value, len), buffer[len] = 0;
Okay.

2022-02-12 11:41 UTC, pontscho commented on src/lib/lwan.c
> +    int logical_cores = 1; sysctlbyname("hw.logicalcpu", &logical_cores, &length, NULL, 0);
In practice those function calls never fails but I will do.

2022-02-13 09:46 UTC, pontscho commented on src/lib/lwan.c
> +                    parse_bool(line->value, default_config.allow_remote_address_override);
I will make this change if you keep this x-real-ip header change. :)

2022-03-03 13:56 UTC, closed without merging